# Generated by Django 5.0 on 2023-12-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPayee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('name_of_doctor', models.CharField(max_length=200)),
                ('tin_no', models.IntegerField()),
                ('hospital_name', models.TextField()),
                ('mobile_no', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'WitholdingTax',
            },
        ),
    ]
