# Generated by Django 5.0 on 2023-12-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_taxpayee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxpayee',
            name='name_of_doctor',
        ),
    ]
